testing changes to staging cicd pipeline

diff --git a/.github/workflows/stage_pipeline.yml b/.github/workflows/stage_pipeline.yml
--- a/.github/workflows/stage_pipeline.yml
+++ b/.github/workflows/stage_pipeline.yml
@@ -2,16 +2,16 @@ name: Staging - Build, deploy, unit and integration test
 
 on:
   pull_request:
-    branches: [staging,master]
-  #push:
-    #branches:
-      #- staging
+    branches: [staging]
+  push:
+    branches: [staging]
 
 
-
+#${{ github.event_name }} == pull_request
 
 jobs:
   build-and-local-test:
+    if: ${{ (github.base_ref == 'staging' && github.event_name == 'pull_request' && github.head_ref == "dev") || (github.base_ref == 'master' &&  github.event_name == 'push') }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -28,6 +28,7 @@ jobs:
         run: |
           python3 -m pytest
   deploy-docker-container-and-test:
+    if: ${{ (github.base_ref == 'staging' && github.event_name == 'pull_request' && github.head_ref == "dev") || (github.base_ref == 'master' &&  github.event_name == 'push') }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -58,10 +59,13 @@ jobs:
           UPDATE_METHOD: merge
           UPDATE_RETRIES: "100"
         run: |
-          if [ ${{github.base_ref}} == 'staging' ]; then
+          if [ ${{github.base_ref}} == 'staging' ] && [ ${{ github.event_name }} == 'pull_request' && github.head_ref == "dev"]; then
             gh pr create --head staging --base master --title "Merge to Prod" --body "This is an automated PR to update prod"
             gh pr merge --auto --merge
-          else
+          elif [ ${{github.base_ref}} == 'master' ] && [ ${{ github.event_name }} == 'push' ]; then
             echo "Merge to prod completed"
             gh pr merge --auto --merge
+          else
+            echo "Error: Pull request must come from 'dev' branch"
+            exit 1
           fi
